--feature-type=mfcc
--add-deltas=false
--global-cmvn-stats=model/vad/global_cmvn.stats
--mfcc-config=model/vad/conf/mfcc_hires.conf
--num-pdf=2
--smooth-win-width=5
--sep-id=0
--min-voice-length=5 
--min-sil-length=40
--max-voice-length=6000 #before is 6000
#--pre-smooth-win-width=2
#--pre-min-voice-length=1
#--max-voice-length=150000   
#--max-length-before-reset=600000
