--inputs-format=input:[batch-size, chunksize, feat-dim]
--inputs-shape=input:[1, 21, 40]
--inputs-dtype=input:float32

--outputs-format=output:[batch-size, output-size, output-dim]
--outputs-shape=output:[1, 1, 2]
--outputs-dtype=output:float32

--multi-threads=false
--infer-thread=false
--num-execute-threads=1
