#--model-path=final.chunk5.onnx
--model-path=final.mdl.onnx
--model-config-path=model.conf
#--scd-model-path=scd
--backend=onnx
--device-type=cpu
--global-cmvn-stats=global_cmvn.stats
--num-pdf=2
--smooth-win-width=5
--sep-id=0
#开始时长
--min-voice-length=25
#尾部静音时长
--min-sil-length=50
--pre-smooth-win-width=2
--pre-min-voice-length=1
--nnet-chunk-size=1
--max-voice-length=6000000
#vad过滤模式：直通模式(0), prebeg模式(1), 长语音模式(2)
--filter-mode=0
#语音流开始时刻增加缓冲的时长
--left-padding-time=336
--smooth-win-frames=5
--pre-smooth-win-frames=2
--min-voice-time=400 #250
--min-sil-time=100 #500
--pre-min-voice-time=10
--max-voice-time=600000000
